export type UserProfile = {
  Company: string;
  Name: string;
  Title: string;
  Department: null | string;
  LinkedIn: string;
  Email: null | string;
  "Preferred Location": string;
  "Current Location": string;
  "Interested in...": null | string;
  "Remote Preference": null | string;
  "Open to Relocation": null | string;
  "Target Company Stage": null | string;
  Discipline: string;
  "Questions? Comments?": null | string;
  "Enrich Person from LinkedIn Profile": string;
  "Name (1)": string;
  "Title (1)": string;
  Org: string;
  Slug: string;
  Connections: null | number;
  "Num Followers": number;
  Headline: string;
  "Picture Url Copy": string;
  Summary: null | string;
  "Url - Experience": string;
  "Title - Experience": string;
  "Org Id - Experience": number;
  "Company - Experience": string;
  "Summary - Experience": null | string;
  "End Date - Experience": string;
  "Locality - Experience": string;
  "Company Id - Experience": null | number;
  "Is Current - Experience": boolean;
  "Start Date - Experience": string;
  "Company Domain - Experience": string;
  "Grade - Education": null | string;
  "Degree - Education": string;
  "End Date - Education": string;
  "Start Date - Education": string;
  "Activities - Education": null | string;
  "School Name - Education": string;
  "Field Of Study - Education": string;
  Country: string;
  "Location Name": string;
  Dob: string | null;
  "Date - Awards": null | string;
  "Title - Awards": null | string;
  "Summary - Awards": null | string;
  "Course Number - Courses": null | string;
  "Title - Courses": null | string;
  "Title - Projects": null | string;
  "Summary - Projects": null | string;
  "End Date - Projects": null | string;
  "Start Date - Projects": null | string;
  "Language - Languages": null | string;
  "Proficiency - Languages": null | string;
  "Last Name": string;
  "Person Id": number;
  "First Name": string;
  "Jobs Count": number;
  "Date - Certifications": null | string;
  "Title - Certifications": null | string;
  "Url - Latest Experience": string;
  "Title - Latest Experience": string;
  "Org Id - Latest Experience": number;
  "Company - Latest Experience": string;
  "Company Name - Certifications": null | string;
  "Company Domain - Latest Experience": string;
  "Current Company": string;
  Unemployed: boolean | "true" | "false";
  Concatenated_Columns: string;
  "Cleaned Skills": string;
};
